package main

import (
	"flag"
	"fmt"
	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
	"log"
	. "revdol/config"
	_ "revdol/docs" // docs is generated by Swag CLI, you have to import it.
)

func init() {
	flag.StringVar(&Config.HttpPort, "p", Config.HttpPort, "http port")
	flag.StringVar(&Config.HttpsPort, "s", Config.HttpsPort, "http port")
	flag.Parse()

	if Config.Gin.Release {
		gin.SetMode(gin.ReleaseMode)
	}
	if Config.Gin.Color{
		gin.ForceConsoleColor()
	}
}

// @title Swagger revdol API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization


// @schemes http https
// @Security ApiKeyAuth

// @host localhost
// @BasePath /v2

func main() {

	r := gin.Default()

	config := &ginSwagger.Config{
		URL: fmt.Sprintf("http://localhost%v/swagger/doc.json", Config.HttpPort),
	}
	r.GET("/swagger/*any", ginSwagger.CustomWrapHandler(config, swaggerFiles.Handler))

	router(r)

	// HTTP
	go func() {
		log.Fatal(r.Run(Config.HttpPort))
	}()

	// HTTPS
	cert, key := certPath()
	log.Fatal(r.RunTLS(Config.HttpsPort, cert, key))
}

func certPath() (cert, key string) {
	return Config.Cert.Cert, Config.Cert.Key
}
