package swagger

import (
	"github.com/gin-gonic/gin"
	_ "github.com/kuhufu/revdol/docs" // docs is generated by Swag CLI, you have to import it.
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

var config = &ginSwagger.Config{
	URL: "/swagger/doc.json",
}

func EnableSwagger(r *gin.Engine) {
	r.GET("/swagger/*any", ginSwagger.CustomWrapHandler(config, swaggerFiles.Handler))
}
