
appname: "revdol"
#是否是开发模式
dev: true

#是否开启 auth
enable_auth: false

cache:
  type: "mem"

gin:
  release: true
  color: true

config:
  #是否在控制台打印配置
  print: true

mongo:
  url: "mongodb://localhost:27017"

redis:
  url: "127.0.0.1:6379"

etcd:
#  url: "127.0.0.1:2379"

gorm:
  log: false
  provider: "mysql"
  url: "root:7266@/revdol?charset=utf8mb4&parseTime=True&loc=Local"

casbin:
  model: "middleware/casbin/model.conf"
  policy: "middleware/casbin/policy.csv"

cert:
  cert_file: "cert/test_cert.pem"
  key_file: "cert/private_key"

http_port: ":80"
https_port: ":443"